from django.conf.urls.defaults import *

urlpatterns = patterns('euscan.views',
    (r'^$', 'index'),
    (r'^about/$', 'about'),
    (r'^statistics/$', 'statistics'),
    (r'^statistics/charts/(?P<chart>[\w\-]+).png$', 'chart'),
    (r'^world/$', 'world'),
    (r'^world/scan/$', 'world_scan'),
    (r'^categories/$', 'categories'),
    (r'^categories/(?P<category>[\w+][\w+.-]*)/view/$', 'category'),
    (r'^categories/(?P<category>[\w+][\w+.-]*)/charts/(?P<chart>[\w\-]+).png$', 'chart_category'),
    (r'^herds/$', 'herds'),
    (r'^herds/(?P<herd>[\{\}\w+.-]*)/view/$', 'herd'),
    (r'^herds/(?P<herd>[\{\}\w+.-]*)/charts/(?P<chart>[\w\-]+).png$', 'chart_herd'),
    (r'^maintainers/$', 'maintainers'),
    (r'^maintainers/(?P<maintainer_id>\d+)/view/$', 'maintainer'),
    (r'^maintainers/(?P<maintainer_id>\d+)/charts/(?P<chart>[\w\-]+).png$', 'chart_maintainer'),
    (r'^package/(?P<category>[\w+][\w+.-]*)/(?P<package>[\w+][\w+.-]*)/$', 'package'),
)
